### ISSUE TITLE
In version 0.40 of hyprland has changed the path to the socket

### ISSUE THREAD

**Issue by TheWhatis** [labi-le/hyprland-ipc-client#5]
**Describe the bug**
In my case, hypr-kbd-layout does not work to dipslay the current layout, 
because it has this package as a dependency, You just need to change the
paths **from /tmp/hypr/{socket} to $XDG_RUNTIME_DIR/hypr/{socket}**

**Desktop:**
 - OS: Arch linux x86_64, Kernel 6.8.7-arch1-2
 - Browser qutebrowser
 - Version 3.1.0

**Comment by labi-le** [comment]
i don't have version 0.40, so it would be good if you check the changes for yourself

**Comment by TheWhatis** [comment]
> i don't have version 0.40, so it would be good if you check the changes for yourself

Yes, everything works, thanks)
